# Generated by Django 4.2.27 on 2025-12-28 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_lookupdata_version1_lookupdata_version2'),
    ]

    operations = [
        migrations.AddField(
            model_name='lookupdata',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
