# Generated by Django 4.2.27 on 2025-12-28 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_lookupdata_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingLookup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('item_type', models.CharField(max_length=20)),
                ('item_value', models.CharField(max_length=100)),
                ('language_context', models.CharField(blank=True, max_length=50, null=True)),
                ('site_visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.sitevisit')),
            ],
        ),
    ]
