# Generated by Django 4.2.27 on 2026-01-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_missinglookup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lookupdata',
            old_name='language1',
            new_name='entry1',
        ),
        migrations.RenameField(
            model_name='lookupdata',
            old_name='language2',
            new_name='entry2',
        ),
    ]
