name: JSON Syntax Validator

on:
  push:
    paths:
      - '**.json'
  pull_request:

jobs:
  check:
    name: Check JSON Files
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: JSON Syntax Check
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"